/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railway.reservation.system;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class BookingDetails extends javax.swing.JFrame {

    /**
     * Creates new form BookingDetails
     */
    public BookingDetails() {
        initComponents();
        this.setTitle("Booking Information");
        Image icon = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Admin\\Documents\\NetBeansProjects\\Railway Reservation System\\src\\images\\icons8-subway-96.png");
        this.setIconImage(icon);
        this.setLocationRelativeTo(null);
        ResultSet rs,r;
        PreparedStatement ps,pstmt;
       
        String query = "select * from reguser where u_uname = '"+UserLogin.name+"'";
        DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
        String bname = null,uid=null;
        try{
         ps = ConnectDb.ConnectionDb().prepareStatement(query);
         r = ps.executeQuery();
         String user = null;
         if(r.next()){
             user = r.getString("u_uname");
             uid = r.getString("u_id");
             System.out.println(user+"  "+uid);
         }
         String sql = "select * from booking_details where b_id ='"+uid+"'";  
         pstmt = ConnectDb.ConnectionDb().prepareStatement(sql);
         rs = pstmt.executeQuery();
         if(rs.next()){
             bname = rs.getString("b_name");
             System.out.println(bname);
         }
        // DefaultTableModel tb = (DefaultTableModel)jTable1.getModel();
         
             
         tb.setRowCount(0);
         rs = pstmt.executeQuery();
         if(user.equals(UserLogin.name)){//&& (bname.equals(fname))
         while(rs.next()){
           Object o[] = {rs.getInt("pnr"),rs.getString("b_name"),rs.getString("train_name"),rs.getString("b_date"),rs.getString("tickets"),rs.getString("class"),rs.getInt("cost")};
           tb.addRow(o);
              
          }
        }else{
         tb.getDataVector().removeAllElements();
         tb.fireTableDataChanged();
         }}catch(Exception e){
            System.out.println(e);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PNR No", "Passenger Name", "Train Name", "Date", "Members", "Class", "Total Fare"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Booking Info");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PanelScreen ps = new PanelScreen();
        ps.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        BillingDetails bill = new BillingDetails();
        int index = jTable1.getSelectedRow();
        TableModel tab = jTable1.getModel();
        
        
        ResultSet rs;
        PreparedStatement pstmt;
        //String sql = "select * from booking_details";
        
            
            String pnr = tab.getValueAt(index, 0).toString();
            String date = tab.getValueAt(index, 3).toString();
            String train = tab.getValueAt(index, 2).toString();
            String cl = tab.getValueAt(index, 5).toString();
            String cost = tab.getValueAt(index, 6).toString();
            String mem = tab.getValueAt(index, 4).toString();
            //System.out.println(train);
            String time = null;
            String trainno = null;
            String query = "select * from train_details where train_name = '"+train+"'";
            try{
            pstmt = ConnectDb.ConnectionDb().prepareStatement(query);
            rs = pstmt.executeQuery();
            if(rs.next()){
                time = rs.getString("time");
                trainno = rs.getString("train_no");
                System.out.println(time+" "+trainno);
            }/*
          bill.jLabelPNR.setText("PNR No:   "+pnr);
          bill.jLabelDate.setText("Journey Date:    "+date);
          bill.jLabelTrain.setText("Train Details:  "+train);
          bill.jLabelClass.setText("Class:  "+cl);
          bill.jLabelCost.setText("Cost:    "+cost);
          bill.jLabelTime.setText("Time:    "+time);*/
        bill.jTextArea1.append("================================================\n"+
        "               **E-Ticket**                    \n"+
        "================================================\n"+
        "PNR No   :   "+pnr+
        "\nDate     :   "+date+
        "\nTime     :   "+time+
        "\nTrain No :   "+trainno+        
        "\nTrain    :   "+train+
        "\nMembers  :   "+mem+        
        "\nClass    :   "+cl+
        "\nCost     :   "+cost);
            
            
        bill.setVisible(true);
        bill.pack();
        bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
            
          }catch(Exception e){
            System.out.println(e);
        }
                
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
